# SPDX-FileCopyrightText: 2022 Simon Wendel
# SPDX-License-Identifier: GPL-3.0-or-later

version: '3.9'

services:
  proxy:
    restart: unless-stopped
    image: nginx:1.27
    volumes:
    - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./proxy/general.conf:/etc/nginx/include/general.conf:ro
    - ./proxy/proxy.conf:/etc/nginx/include/proxy.conf:ro
    - ./proxy/security.conf:/etc/nginx/include/security.conf:ro
    - ./proxy/log.conf:/etc/nginx/include/log.conf:ro
    - ./proxy/templates:/etc/nginx/templates:ro
    - ./proxy/reload.sh:/docker-entrypoint.d/reload.sh:ro
    - certbot_conf_vol:/etc/letsencrypt:ro
    - certbot_www_vol:/var/www/certbot:ro
    - proxy_logs_vol:/var/log/nginx
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
      - API_DOMAIN=${API_DOMAIN}
    networks:
    - default
    - app_net
    - api_net
    ports:
    - '80:80'
    - '443:443'

  app:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ../frontend
      args:
      - ELM_CONFIG_API=https://${API_DOMAIN}
      - ELM_ENVIRONMENT=Production
    networks:
    - app_net
    expose:
    - '80'

  api:
    restart: unless-stopped
    build:
      dockerfile: Api/Dockerfile
      context: ../backend
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80
      API_API__CORS__ALLOWORIGINS__0: ${APP_DOMAIN}
    networks:
    - api_net
    - db_net
    expose:
    - '80'

  db:
    restart: unless-stopped
    image: mongo:8.0
    volumes:
    - database_vol:/data/db
    networks:
    - db_net
    expose:
    - '27017'

  certbot:
    restart: unless-stopped
    image: certbot/certbot:v3.1.0
    entrypoint: |
      /bin/ash -c 'trap exit TERM; while true; do certbot renew; sleep 12h; done;'
    volumes:
    - certbot_conf_vol:/etc/letsencrypt
    - certbot_www_vol:/var/www/certbot

networks:
  default:
  app_net:
    internal: true
  api_net:
    internal: true
  db_net:
    internal: true

volumes:
  database_vol:
  certbot_conf_vol:
  certbot_www_vol:
  proxy_logs_vol:
